# Generated by Django 4.2.1 on 2023-10-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=225)),
                ('book_auther', models.CharField(max_length=225)),
                ('book_page', models.CharField(max_length=225)),
            ],
        ),
    ]
