# Generated by Django 4.2.1 on 2023-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_page',
        ),
        migrations.AddField(
            model_name='books',
            name='book_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_auther',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
