# Generated by Django 4.2.1 on 2024-01-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_full_name_remove_student_roll_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='student_roll',
            field=models.IntegerField(null=True),
        ),
    ]
