# Generated by Django 4.2.1 on 2024-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_additional_remove_student_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_study_program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='valid_email',
        ),
        migrations.AddField(
            model_name='student',
            name='bookpricet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='booktiti',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
